config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admin/sessions'
  }
  devise_for :users, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations'
  }

  namespace :admin do
    resources :books, only: %i[index show new create edit update destroy] do
      collection do
        get 'search'
      end
    end
  end

  scope module: :user do
    resources :books, only: %i[index show] do
      resources :posts, only: %i[new create edit update] do
        resources :likes, only: %i[create destroy]
      end
    end
  end
  resources :users, only: %i[show edit update]
  root "pages#home"
  get "about" , to: "pages#about"
  get "privacy_policy", to: "pages#privacy_policy"
  get "terms" , to: "pages#terms"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/book.rb
class Book < ApplicationRecord
  HOME_PAGE_DISPLAY_LIMIT = 12

  has_one_attached :image
  has_many :posts, dependent: :destroy

  validate :image_presence

  scope :with_average_difficulty_between, ->(min, max) {
    joins(:posts)
      .select("books.*, COUNT(posts.id) AS posts_count, AVG(posts.difficulty) AS average_difficulty")
      .group("books.id")
      .having("AVG(posts.difficulty) BETWEEN ? AND ?", min, max)
  }

  # NOTE: with_average_difficulty_between の後でのみ使用可能（posts_count は仮想カラムであるため）
  scope :ordered_by_posts_count, -> { order(posts_count: :desc) }

  scope :limit_for_home, -> { limit(HOME_PAGE_DISPLAY_LIMIT) }

  scope :latest, -> { order(published_day: :desc) }

  def avg_difficulty
    unless self.posts.empty?
      posts.average(:difficulty).round(1).to_f
    else
      0.0
    end
  end

  def post_difficulty_percentage
    unless self.posts.empty?
      posts.average(:difficulty).round(1).to_f*100/5
    else
      0.0
    end
  end

  ransacker :posts_count do
    Arel.sql('(
      SELECT COUNT(posts.id) FROM posts WHERE posts.book_id = books.id
    )')
  end

  ransacker :avg_difficulty, type: :float do
    Arel.sql('(
      SELECT COALESCE(ROUND(AVG(posts.difficulty), 1), 0)
      FROM posts
      WHERE posts.book_id = books.id
    )')
  end

  # ransack用の検索対象フィールドを指定する
  def self.searchable_attributes
    %w[title author category published_day posts_count avg_difficulty]
  end
  searchable_attributes.each do |field|
    scope "search_by_#{field}", ->(keyword) { where("#{field} LIKE ?", "%#{keyword}%") }
  end
  
  def self.ransackable_attributes(auth_object = nil)
   ["title","author","category","published_day","posts_count","avg_difficulty"] # 検索可能な属性名を指定
  end

  def self.ransackable_associations(auth_object = nil)
    ["posts"] # 検索可能な関連名を指定
  end

  private

  def image_presence
    errors.add(:image, "を添付してください") unless image.attached?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable
  devise authentication_keys: [:custom_id]
  before_create :generate_custom_id
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :icon
  validates :name, presence: true, length: { maximum: 100 }
  validates :self_introduction, length: { maximum: 200 }
  validates :level, inclusion: { in: ["初級エンジニア", "中級エンジニア", "上級エンジニア"] }, allow_blank: true

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

  private

  def generate_custom_id
    loop do
      self.custom_id = SecureRandom.random_number(100000..999999).to_s
      break unless User.exists?(custom_id: custom_id)
    end
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_book, only: %i[show edit update destroy]

  def index
    @books = Book.all
  end

  def show; end

  def new
    @book = Book.new
  end

  def edit; end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to admin_books_path
    else
      render :new
    end
  end

  def update
    if @book.update(book_params)
      redirect_to admin_books_path
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to admin_books_path
  end

  def search
    @book = SearchGoogleBooksService.call(params[:title])

    if @book.nil?
      @book = Book.new
      @error_message = "本が見つかりませんでした。"
    end

    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(
      :title, :description, :image, :volume, :published_day, :language,
      :company, :link ,:author ,:category
    )
  end
end

app/controllers/user/books_controller.rb
class User::BooksController < ApplicationController
  def index
    @q = Book.ransack(params[:q])
    @categories = Book.distinct.pluck(:category)
    @books = @q.result(distinct: true).page(params[:page]).per(10)
  end

  def show
    @book = Book.find(params[:id])
    @posts = @book.posts
    if user_signed_in?
      @user_post = current_user.posts.find_by(book_id: @book.id)
      @like = Like.new
    end
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/likes_controller.rb
class User::LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    like = @post.likes.new(user_id: current_user.id)
    like.save
  end

  def destroy
    @post = Post.find(params[:post_id])
    like = current_user.likes.find_by(post_id: @post.id)
    like.destroy
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_book_and_post, only: %i[edit update]
  before_action :authorize_user!, only: %i[edit update]

  def new
    @post = Post.new
    @book = Book.find(params[:book_id])
  end

  def edit
  end

  def create
    @book = Book.find(params[:book_id])
    @post = @book.posts.build(post_params) # @bookに関連する投稿を作成
    @post.user_id = current_user.id
    if @post.save
      redirect_to book_path(@book)
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  private
  def set_book_and_post
    @book = Book.find(params[:book_id])
    @post = @book.posts.find(params[:id])
  end

  def authorize_user!
    redirect_to root_path, alert: "この投稿を編集する権限がありません。" if @post.user_id != current_user.id
  end

  def post_params
    params.require(:post).permit(:difficulty, :content)
  end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  def create
    super do |resource|
      # resource が保存に成功していれば、flash に custom_id をセット
      flash[:custom_id] = resource.custom_id if resource.persisted?
    end
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update]
  before_action :authenticate_user!, only: %i[edit update]
  before_action :authorize_user!, only: %i[edit update]
  def show
    @books = Book.joins(:posts).where(posts: { user_id: @user.id }).distinct.page(params[:page]).per(16)
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def authorize_user!
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user), alert: "このプロフィールを編集する権限がありません。"
    end
  end

  def user_params
    params.require(:user).permit(:name, :self_introduction, :x_url, :github_url, :level ,:icon)
  end
end

app/helpers/user/likes_helper.rb
module User::LikesHelper
end

app/helpers/user/posts_helper.rb
module User::PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/user/books/_search.html.erb
<%= search_form_for @q, url: books_path, method: :get, class: "row g-3 align-items-center" do |f| %>
  
  <div class="col-md-4">
    <div class="form-floating">
      <%= f.search_field :title_or_author_cont, 
          class: "form-control", 
          placeholder: "キーワード検索" %>
      <label for="q_title_or_author_cont">キーワード検索</label>
    </div>
  </div>

  <div class="col-md-3">
    <div class="form-floating">
      <%= f.select :category_eq, 
          options_for_select(@categories), 
          { include_blank: '選択してください' }, 
          class: "form-select" %>
      <label for="q_category_eq">カテゴリー</label>
    </div>
  </div>

  <div class="col-md-2">
    <div class="form-floating">
      <%= f.select :avg_difficulty_gteq, 
          options_for_select((0..10).map { |n| [sprintf('%.1f', n * 0.5), n * 0.5] }, @q.avg_difficulty_gteq),
          { include_blank: '選択してください' }, 
          class: "form-select" %>
      <label for="q_avg_difficulty_gteq">難易度(以上)</label>
    </div>
  </div>

  <div class="col-md-2">
    <div class="form-floating">
      <%= f.select :avg_difficulty_lteq, 
          options_for_select((0..10).map { |n| [sprintf('%.1f', n * 0.5), n * 0.5] }, @q.avg_difficulty_lteq),
          { include_blank: '選択してください' }, 
          class: "form-select" %>
      <label for="q_avg_difficulty_lteq">難易度(以下)</label>
    </div>
  </div>

  <div class="col-md-1 d-grid">
    <%= f.submit '検索', class: "btn btn-orange" %>
  </div>

  <div class="col-12 mt-3">
    <div class="btn-group" role="group" aria-label="Sort options">
      <%= sort_link(@q, :published_day, "出版年順", { default_order: :desc }, class: "btn btn-outline-secondary btn-outline-orange") %>
      <%= sort_link(@q, :posts_count, "レビュー数順", { default_order: :desc }, class: "btn btn-outline-secondary btn-outline-orange") %>
    </div>
  </div>
<% end %>

app/views/user/books/index.html.erb
<div class="container mt-4">
  <h2 class="mb-4 text-center">本を探す</h2>

  <div class="mb-4">
    <%= render 'user/books/search' %>
  </div>

  <% @books.each do |book| %>
    <div class="card mb-4 search-card">
      <%= link_to book_path(book), class: "text-decoration-none text-dark" do %>
        <div class="row">
          
          <div class="col-md-3 d-flex align-items-center justify-content-center p-3">
            <%= image_tag book.image, class: "img-fluid rounded-start book-img", alt: book.title %>
          </div>
          
          <div class="col-md-9">
            <div class="card-body">
              <h5 class="search-card-title mb-2"><span><%= book.title %><span></h5>
              <p class="card-text text-muted mb-2">
                <%= book.author %> | <%= book.published_day.strftime("%Y-%m-%d") %>
              </p>
              <div class="difficulty_rating mb-3">
                <p class="difficulty-level mb-1">難易度Lv: <%= book.avg_difficulty %></p>
                <div class="difficulty-icons mb-2">
                  <% 1.upto(5) do |i| %>
                    <% if book.avg_difficulty >= i %>
                      <i class="bi bi-book-fill icon-active"></i>
                    <% elsif book.avg_difficulty < i - 1 %>
                      <i class="bi bi-book-fill icon-inactive"></i>
                    <% else %>
                      <% fraction = book.avg_difficulty - (i - 1) %>
                      <span class="icon-partial-wrapper">
                        <i class="bi bi-book-fill icon-inactive"></i>
                        <i class="bi bi-book-fill icon-active partial-fill" style="width: <%= (fraction * 100).round %>%"></i>
                      </span>
                    <% end %>
                  <% end %>
                </div>
              </div>
              <p class="card-text text-muted mb-1">レビュー数：<%= book.posts.count %></p>
              <p class="card-text text-muted">カテゴリー：<%= book.category %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

  <div class="d-flex justify-content-center">
    <%= paginate @books, theme: 'bootstrap-5' %>
  </div>
</div>

app/views/user/books/show.html.erb
<main class="container mt-4">
    <div class="row">
        <div class="col-md-3">
            <div class="book-info text-center">
                <%= image_tag @book.image ,class:"book-img-top"%>
                <h5 class="mt-3"><%= @book.title%></h5>
                <p><%= @book.author%></p>
            </div>
            
            <div class="side-section">
                <h6>その他情報</h6>
                <p>カテゴリー: <%= @book.category%></p>
                <p>出版日: <%= @book.published_day%></p>
                <p>ページ数: <%= @book.volume%></p>
                <p>言語: <%= @book.language%></p>
                <p>出版社: <%= @book.company%></p>
                <a href="<%= @book.link%>" target="_blank" rel="noopener noreferrer">Amazon Link </a>
            </div>
        </div>

        <div class="col-md-9">
            <section class="mb-4 show-difficulty">
                <h4>難易度Lv: <%= @book.avg_difficulty%></h4>
                <div class="difficulty-icons mb-2">
                    <% 1.upto(5) do |i| %>
                        <% if @book.avg_difficulty >= i %>
                            <i class="bi bi-book-fill show-icon-active"></i>
                        <% elsif @book.avg_difficulty < i - 1 %>
                            <i class="bi bi-book-fill show-icon-inactive"></i>
                        <% else %>
                            <% fraction = @book.avg_difficulty - (i - 1) %>
                            <span class="icon-partial-wrapper">
                                <i class="bi bi-book-fill show-icon-inactive"></i>
                                <i class="bi bi-book-fill show-icon-active partial-fill" style="width: <%= (fraction * 100).round %>%"></i>
                            </span>
                        <% end %>
                    <% end %>
                </div>
            </section>

            <section>
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h4>ユーザーのレビュー</h4>
                    <% if user_signed_in? %>
                        <% if @user_post.present?%>
                            <%= link_to edit_book_post_path(@book, @user_post), class: "btn btn-orange" do %>
                                レビューを編集
                            <% end %>
                        <% else %>
                            <%= link_to new_book_post_path(@book), class: "btn btn-orange" do %>
                                レビューを投稿
                            <% end %>
                        <% end %>
                    <% else %>
                        <%= link_to new_user_session_path, class: "btn btn-orange" do %>
                            レビューを投稿
                        <% end %>
                    <% end %>
                </div>
                
                <% @posts.each do |post| %>
                    <div class="card mb-3">
                        <div class="card-header d-flex align-items-start justify-content-between">
                            <div class="d-flex align-items-center">
                                <%= link_to user_path(post.user) do %>
                                    <% if post.user.icon.attached? %>
                                        <%= image_tag post.user.icon ,class:"icon-img rounded-circle me-2"%>
                                    <% else %>
                                        <%= image_tag 'default_icon.webp',class:"icon-img rounded-circle me-2"%>
                                    <% end %>
                                    <strong><%= post.user.name %></strong>
                                    <span class="ms-1 text-muted"><%= post.user.level %></span>
                                <% end %>
                            </div>
                            <small class="text-muted"><%= post.created_at.strftime('%Y/%m/%d') %></small>
                        </div>
                        <div class="card-body" data-controller="read-more">
                            <div class="mb-2">
                                <span>難易度Lv: <%= post.difficulty%></span>
                                <div class="difficulty-icons mb-2">
                                    <% 1.upto(5) do |i| %>
                                        <% if post.difficulty >= i %>
                                            <i class="bi bi-book-fill icon-active"></i>
                                        <% else %>
                                            <i class="bi bi-book-fill icon-inactive"></i>
                                        <% end %>
                                    <% end %>
                                </div>
                            </div>
                            <p class="post-content card-text mb-2" data-read-more-target="content"><%= post.content %></p>
                            <button class="btn btn-link p-0 read-more-button"
                            data-read-more-target="expandButton"
                            data-action="click->read-more#expand">続きを読む</button>
                            <button class="btn btn-link p-0 read-more-button"
                            data-read-more-target="collapseButton"
                            data-action="click->read-more#collapse">閉じる</button>
                            <% if user_signed_in? %>
                                <div class="text-muted" id="like_btn_<%= post.id %>">
                                    <%= render "user/likes/btn", post: post %>
                                </div>
                            <% else %>
                                <div class="text-muted" id="like_btn_<%= post.id %>">
                                    <i class="fa-regular fa-heart" aria-hidden="true"></i>
                                    <%= post.likes.count %> いいね
                                </div>
                            <% end %>
                        </div>
                    </div>
                <% end %>
            </section>
        </div>
    </div>
</main>