config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admin/sessions'
  }
  devise_for :users, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations'
  }

  namespace :admin do
    resources :books, only: %i[index show new create edit update destroy] do
      collection do
        get 'search'
      end
    end
  end

  scope module: :user do
    resources :books, only: %i[index show] do
      resources :posts, only: %i[new create edit update] do
        resources :likes, only: %i[create destroy]
      end
    end
  end
  resources :users, only: %i[show edit update]
  root "pages#home"
  get "about" , to: "pages#about"
  get "privacy_policy", to: "pages#privacy_policy"
  get "terms" , to: "pages#terms"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/_footer.html.erb
<footer class="bg-light py-3 mt-5">
  <div class="container">
    <div class="row text-center">
      <div class="col">
        <a href="/privacy_policy" class="text-decoration-none text-muted me-3">プライバシーポリシー</a>
        <a href="/terms" class="text-decoration-none text-muted me-3">利用規約</a>
        <a href="https://docs.google.com/forms/d/e/1FAIpQLSd0-RgE2Shsk3frkvhzsw-yU-hGXKU-iTM--gh8dbaAw8e1JQ/viewform?usp=dialog" target="_blank" rel="noopener noreferrer" class="text-decoration-none text-muted">お問い合わせフォーム</a>
      </div>
    </div>
    <div class="row">
        <div class="col text-center">
            <small class="text-muted">Copyright © 2025 TechBook Finder - All right reserved</small>
        </div>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg custom-navbar">
  <div class="container">
    <%= link_to root_path, class: "navbar-brand custom-brand" do %>
      <span class="brand-text">TechBook Finder</span>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarContent">
      <ul class="navbar-nav ms-auto">
        <% if admin_signed_in? %>
          <li class="nav-item">
            <%= link_to new_admin_book_path, class: "nav-link" do %>
              本の投稿
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_admin_session_path, data: { turbo_method: :delete }, class: "nav-link" do %>
              Sign out
            <% end %>
          </li>
        <% elsif user_signed_in? %>
          <li class="nav-item">
            <%= link_to books_path, class: "btn btn-orange" do %>
              <i class="fa-solid fa-magnifying-glass"></i> 本を探す
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to "About", about_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "マイページ", user_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" do %>
              Sign out
            <% end %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to books_path, class: "btn btn-orange" do %>
              <i class="fa-solid fa-magnifying-glass"></i> 本を探す
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to "About", about_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechBook Finder</title>
    <%= favicon_link_tag 'favicon.jpg' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://kit.fontawesome.com/c90134f9a2.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </head>

  <body class="d-flex flex-column min-vh-100">
    <%= render 'layouts/navbar'%>
    
    <% if flash[:custom_id].present? %>
      <div class="container mt-3">
        <div class="alert alert-info alert-dismissible fade show" role="alert">
          あなたのカスタムIDは <h4 class="d-inline"><%= flash[:custom_id] %></h4> です。<br>
          このカスタムIDはログインの際に必要です！コピーしてメモ帳に保存することをおすすめします。
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>

    <main class="flex-fill">
      <%= yield %>
    </main>

    <%= render 'layouts/footer'%>
  </body>
</html>